apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{- $auth := printf "%s:%s" .Values.raven.docker.username .Values.raven.docker.password | b64enc }}
    {{- $config := dict "auths" (dict .Values.raven.docker.server (dict "username" .Values.raven.docker.username "password" .Values.raven.docker.password "auth" $auth)) }}
    {{ $config | toJson | b64enc }}