raven:
  # Your Raven licence key
  licenseKey: ""

  # Raven docker images config
  compact:
    image:
      repository: ghcr.io/dragonisle/raven-compact
      tag: ""
  dashboard:
    image:
      repository: ghcr.io/dragonisle/raven-ui
      tag: ""
  # Postgres service name, password secret name and key
  # Default value are the ones created by bitnami postgres chart,
  # with a release name 'raven-setup-postgresql'
  postgres:
    service: raven-setup-rw
    secret: raven-setup-app
    secretKeyUser: user
    secretKeyPw: password
    secretKeyDb: dbname
  # Clickhouse service name, password secret name and key
  # Default value are the ones created by bitnami clickhouse chart,
  # with a release name 'raven-setup-clickhouse'
  clickhouse:
    service: raven-setup-clickhouse
    secret: raven-setup-clickhouse
    secretKey: admin-password
  # Redis service name, password secret name and key
  # Default value are the ones created by bitnami redis chart,
  # with a release name 'raven-setup-redis'
  redis:
    service: raven-setup-dragonfly
  #    secret: raven-setup-redis
  #    secretKey: redis-password

  # Alert management external outputs config, if some conf is enabled - other fields should be provided as well,
  # ex. for slack - webhookUrl is required
  externalOutputs:
    slack:
      enabled: false
      # https://docs.slack.dev/messaging/sending-messages-using-incoming-webhooks/
      webhookUrl: ""
    email:
      enabled: false
      # List of emails to send alerts to
      mails: []
      # Email from which alerts will be sent (should correspond to email provider allowed domain)
      emailFrom: ""
      smtpUser: ""
      smtpPassword: ""
      smtpHost: ""
      smtpPort: 587

  # AI logs aggregation config
  aggregation:
    # Logs will be aggregated per each 'windowTimeRange' period of time
    windowTimeRange: 1 minute
    # Logs can arrive not later than [current timestamp - 'batchMaxRetention'],
    # after batchMaxRetention - batch is finalised
    batchMaxRetention: 3 minutes
    # Real-time data drift alerts reference period
    dataDriftReferencePeriod: 1 hour

  # Alerts triggering thresholds and coefficients
  aiAlerts:
    # Single log alerting thresholds
    singleLog:
      confidenceThreshold: 0.7
      responseTimeThreshold: 500 milliseconds
    aggregatedLogs:
      # Aggregated logs mean values alerting thresholds
      confidenceThreshold: 0.8
      responseTimeThreshold: 400 milliseconds
      eventAmountThresholdCoeff: 0.5
      # Data drift alerting thresholds
      drift:
        zScoreThreshold: 3.0
        deltaMeanThreshold: 0.2
        jsDivergenceThreshold: 0.05