apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init-sql
  annotations:
    "helm.sh/hook": pre-install
data:
  init.sql: |-
    {{ .Files.Get "files/init.sql" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-job-config
  annotations:
    "helm.sh/hook": pre-install
data:
  flink-job.conf: |-
    {{ tpl (.Files.Get "files/flink-job.conf") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-manager-config
  annotations:
    "helm.sh/hook": pre-install
data:
  application.conf: |-
    {{ tpl (.Files.Get "files/alert-manager.conf") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-analyzer-config
  annotations:
    "helm.sh/hook": pre-install
data:
  application.conf: |-
    {{ tpl (.Files.Get "files/metrics-analyzer.conf") . | nindent 4 }}
{{- if .Values.raven.docker }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{- $auth := printf "%s:%s" .Values.raven.docker.username .Values.raven.docker.password | b64enc }}
    {{- $config := dict "auths" (dict .Values.raven.docker.server (dict "username" .Values.raven.docker.username "password" .Values.raven.docker.password "auth" $auth)) }}
    {{ $config | toJson | b64enc }}
{{- end }}
