raven:
  # Your Raven licence key
  licenseKey: ""

  # Docker credentials for pulling images (do not touch it until necessary, by default images should be available without it)
  #  docker:
  #    server:
  #    username:
  #    password:
  # Image pull secrets used to fetch raven images
  # (ghrc-secret is the secret automatically created from the above docker credentials),
  # by default images should available without it
  #  imagePullSecrets:
  #    - name: ghcr-secret

  # Postgres service name, password secret name and key
  postgres:
    service: raven-setup-postgresql
    secret: raven-setup-postgresql
    secretKey: postgres-password
  # Clickhouse service name, password secret name and key
  clickhouse:
    service: raven-setup-clickhouse
    secret: raven-setup-clickhouse
    secretKey: admin-password

  # Kafka service name and raven AI logs topic config
  kafka:
    service: raven-setup-kafka
    topicName: ai-logs
    partitions: 3
    replicationFactor: 1
  # Flink service name
  flink:
    service: raven-setup-flink-rest
  # Raven Flink job version and token to get it
  flinkJob:
    version: 0.1.21-SNAPSHOT
    githubToken:

  # AI logs aggregation config
  aggregation:
    windowTimeRange: 1 minute
    batchMaxRetention: 3 minutes
    dataDriftReferencePeriod: 1 hour

  # Alerts triggering thresholds and coefficients
  aiAlerts:
    singleLog:
      confidenceThreshold: 0.7
      responseTimeThreshold: 500 milliseconds
    aggregatedLogs:
      confidenceThreshold: 0.8
      responseTimeThreshold: 400 milliseconds
      eventAmountThresholdCoeff: 0.5
      drift:
        zScoreThreshold: 3.0
        deltaMeanThreshold: 0.2
        jsDivergenceThreshold: 0.05

  alertsManager:
    image:
      repository:
      tag: 0.1.13-SNAPSHOT
    # Alert manager external outputs config, if some conf is enabled - other fields should be provided as well,
    # ex. for slack - webhookUrl is required
    externalOutputs:
      slack:
        enabled: false
        webhookUrl: ""
      email:
        enabled: false
        mails: [ ]
        smtpUser: ""
        smtpPassword: ""
        smtpHost: ""
        smtpPort: 587
        emailFrom: ""
  metricsAnalyzer:
    image:
      repository: ghcr.io/dragonisle/raven-metrics-analyzer
      tag: 0.1.13-SNAPSHOT
  dashboard:
    image:
      repository: ghcr.io/dragonisle/raven-ui
      tag: 0.1.2
